2020-12-10 11:46:50.1799|ERROR|WebApiKaeser.Factory.SeguridadDataBase|Error en Get_validar_usuarios: La conversión especificada no es válida.
2020-12-10 12:40:35.2149|ERROR|WebApiKaeser.Factory.BaseDataBase|Get_list_caracteristicaValor: CVA_CVA_PADRE_ID 
2020-12-10 12:40:35.2489|ERROR|WebApiKaeser.Factory.BaseDataBase|Get_list_caracteristicaValor: CVA_CVA_PADRE_ID 
2020-12-10 12:40:42.7221|ERROR|WebApiKaeser.Factory.TransaccionDataBase|Error en : Índice fuera de los límites de la matriz.Set_Asignar_ValoresActivos
2020-12-10 12:40:53.3421|ERROR|WebApiKaeser.Factory.TransaccionDataBase|Error en : Índice fuera de los límites de la matriz.Set_Asignar_ValoresActivos
2020-12-10 12:46:05.9345|ERROR|WebApiKaeser.Factory.TransaccionDataBase|Error en : Índice fuera de los límites de la matriz.Set_Asignar_ValoresActivos
2020-12-10 12:51:46.4981|ERROR|WebApiKaeser.Factory.TransaccionDataBase|Error en : Índice fuera de los límites de la matriz.Set_Asignar_ValoresActivos
2020-12-10 12:52:38.1706|ERROR|WebApiKaeser.Factory.TransaccionDataBase|Error en : Índice fuera de los límites de la matriz.Set_Asignar_ValoresActivos
2020-12-10 12:52:57.1299|ERROR|WebApiKaeser.Factory.BaseDataBase|Get_list_caracteristicaValor: CVA_CVA_PADRE_ID 
2020-12-10 12:52:57.1809|ERROR|WebApiKaeser.Factory.BaseDataBase|Get_list_caracteristicaValor: CVA_CVA_PADRE_ID 
2020-12-10 12:52:57.2249|ERROR|WebApiKaeser.Factory.BaseDataBase|Get_list_caracteristicaValor: CVA_CVA_PADRE_ID 
2020-12-10 12:52:57.2669|ERROR|WebApiKaeser.Factory.BaseDataBase|Get_list_caracteristicaValor: CVA_CVA_PADRE_ID 
2020-12-10 12:52:57.3079|ERROR|WebApiKaeser.Factory.BaseDataBase|Get_list_caracteristicaValor: CVA_CVA_PADRE_ID 
2020-12-10 12:55:30.9286|ERROR|WebApiKaeser.Factory.BaseDataBase|Get_list_caracteristicaValor: CVA_CVA_PADRE_ID 
2020-12-10 12:55:31.0586|ERROR|WebApiKaeser.Factory.BaseDataBase|Get_list_caracteristicaValor: CVA_CVA_PADRE_ID 
2020-12-10 12:58:29.7243|ERROR|WebApiKaeser.Factory.TransaccionDataBase|Error en : Índice fuera de los límites de la matriz.Set_Asignar_ValoresActivos
2020-12-10 12:59:05.1212|ERROR|WebApiKaeser.Factory.TransaccionDataBase|Error en : Índice fuera de los límites de la matriz.Set_Asignar_ValoresActivos
2020-12-10 12:59:41.0209|ERROR|WebApiKaeser.Factory.TransaccionDataBase|Error en : Índice fuera de los límites de la matriz.Set_Asignar_ValoresActivos
2020-12-10 13:00:00.5954|ERROR|WebApiKaeser.Factory.TransaccionDataBase|Error en : Índice fuera de los límites de la matriz.Set_Asignar_ValoresActivos
2020-12-10 13:01:05.6645|ERROR|WebApiKaeser.Factory.TransaccionDataBase|Error en : Índice fuera de los límites de la matriz.Set_Asignar_ValoresActivos
2020-12-10 13:04:15.8400|ERROR|WebApiKaeser.Factory.TransaccionDataBase|Error en : Índice fuera de los límites de la matriz.Set_Asignar_ValoresActivos
2020-12-10 13:10:36.3404|ERROR|WebApiKaeser.Factory.TransaccionDataBase|Error en : Índice fuera de los límites de la matriz.Set_Asignar_ValoresActivos
2020-12-10 13:14:12.8150|ERROR|WebApiKaeser.Factory.TransaccionDataBase|Error en : Guid debe contener 32 dígitos con 4 guiones (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).Set_Asignar_ValoresActivos
2020-12-10 13:34:48.6801|ERROR|WebApiKaeser.Factory.SeguridadDataBase|Sql error en Get_list_permisos: Error en el nivel del transporte al recibir los resultados del servidor. (provider: TCP Provider, error: 0 - Se agotó el tiempo de espera del semáforo.)
2020-12-10 13:35:05.7245|ERROR|WebApiKaeser.Factory.SeguridadDataBase|Error en Get_list_permisos: Valor de tiempo de espera caducado. El período de tiempo de espera expiró antes de obtener una conexión del grupo. Esto puede suceder porque todas las conexiones de la agrupación estaban en uso y se alcanzó el máximo tamaño del grupo.
2020-12-10 13:35:17.1011|ERROR|WebApiKaeser.Factory.SeguridadDataBase|Sql error en Get_list_permisos: Error relacionado con la red o específico de la instancia mientras se establecía una conexión con el servidor SQL Server. No se encontró el servidor o éste no estaba accesible. Compruebe que el nombre de la instancia es correcto y que SQL Server está configurado para admitir conexiones remotas. (provider: Named Pipes Provider, error: 40 - No se pudo abrir una conexión con SQL Server)
2020-12-10 13:35:17.1011|ERROR|WebApiKaeser.Factory.InformesDataBase|Sql error en Get_list_Dashboard_ActivosFijos: Error relacionado con la red o específico de la instancia mientras se establecía una conexión con el servidor SQL Server. No se encontró el servidor o éste no estaba accesible. Compruebe que el nombre de la instancia es correcto y que SQL Server está configurado para admitir conexiones remotas. (provider: Named Pipes Provider, error: 40 - No se pudo abrir una conexión con SQL Server)
2020-12-10 13:35:17.1011|ERROR|WebApiKaeser.Factory.InformesDataBase|Sql error en Get_list_Dashboard_Retornables_Diario: Error relacionado con la red o específico de la instancia mientras se establecía una conexión con el servidor SQL Server. No se encontró el servidor o éste no estaba accesible. Compruebe que el nombre de la instancia es correcto y que SQL Server está configurado para admitir conexiones remotas. (provider: Named Pipes Provider, error: 40 - No se pudo abrir una conexión con SQL Server)
2020-12-10 13:35:26.1403|ERROR|WebApiKaeser.Factory.SeguridadDataBase|Sql error en Get_list_permisos: Error relacionado con la red o específico de la instancia mientras se establecía una conexión con el servidor SQL Server. No se encontró el servidor o éste no estaba accesible. Compruebe que el nombre de la instancia es correcto y que SQL Server está configurado para admitir conexiones remotas. (provider: Named Pipes Provider, error: 40 - No se pudo abrir una conexión con SQL Server)
2020-12-10 13:36:53.7120|ERROR|WebApiKaeser.Factory.SeguridadDataBase|Sql error en Get_validar_usuarios: Error relacionado con la red o específico de la instancia mientras se establecía una conexión con el servidor SQL Server. No se encontró el servidor o éste no estaba accesible. Compruebe que el nombre de la instancia es correcto y que SQL Server está configurado para admitir conexiones remotas. (provider: Named Pipes Provider, error: 40 - No se pudo abrir una conexión con SQL Server)
2020-12-10 13:37:07.1716|ERROR|WebApiKaeser.Factory.SeguridadDataBase|Sql error en Get_validar_usuarios: Error relacionado con la red o específico de la instancia mientras se establecía una conexión con el servidor SQL Server. No se encontró el servidor o éste no estaba accesible. Compruebe que el nombre de la instancia es correcto y que SQL Server está configurado para admitir conexiones remotas. (provider: Named Pipes Provider, error: 40 - No se pudo abrir una conexión con SQL Server)
